/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my_currency_converter;

import javax.swing.JOptionPane;

/**
 *
 * @author Tharindu Dhananjaya
 */
public class mycurrencyconverter extends javax.swing.JFrame {
    
        double Sri_Lankan_Rupees = 399.24;
        double US_Dollar = 1.23;
        double Canadian_Dollar = 1.67;
        double Japanese_Yen = 183.69;
        double Italy_Euro = 0.86;
        double Russian_Ruble = 119.66;
        double Australian_Dollar = 1.92;
        double Chinese_Yuan = 8.83;
        double South_Korean_Won = 1648.56;
        double Philippine_Peso = 69.92;
    
    String[] currencyUnits = {
        "units",
        "Sri Lankan Rupees",
        "US Dollar",
        "Canadian Dollar",
        "Japanese Yen",
        "Italy Euro",
        "Russian Ruble",
        "Australian Dollar",
        "Chinese Yuan",
        "South Korean Won",
        "Philippine Peso"
    };
    
    /*
      Creates new form mycurrencyconverter
     */
    public mycurrencyconverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        firstcountry = new javax.swing.JComboBox<>();
        secondcountry = new javax.swing.JComboBox<>();
        txtfirst = new javax.swing.JTextField();
        txtsecond = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        firstcurrencyunit = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        secondcurrencyunit = new javax.swing.JLabel();
        btnconvert = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Currency Converter");

        firstcountry.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        firstcountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one...", "Sri Lanka", "USA", "Canada", "Japan", "Italy", "Russia", "Australia", "China", "South Korea", "Philippine" }));
        firstcountry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                firstcountryItemStateChanged(evt);
            }
        });

        secondcountry.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        secondcountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one...", "Sri Lanka", "USA", "Canada", "Japan", "Italy", "Russia", "Australia", "China", "South Korea", "Philippine" }));
        secondcountry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                secondcountryItemStateChanged(evt);
            }
        });

        txtfirst.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtsecond.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("From currency of");

        firstcurrencyunit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstcurrencyunit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstcurrencyunit.setText("units");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("To currency of");

        secondcurrencyunit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        secondcurrencyunit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        secondcurrencyunit.setText("units");

        btnconvert.setBackground(new java.awt.Color(51, 204, 255));
        btnconvert.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnconvert.setText("Convert");
        btnconvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconvertActionPerformed(evt);
            }
        });

        btnreset.setBackground(new java.awt.Color(255, 255, 153));
        btnreset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        btnexit.setBackground(new java.awt.Color(255, 153, 153));
        btnexit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstcurrencyunit, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(234, 234, 234)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnexit)
                                    .addComponent(txtsecond)
                                    .addComponent(secondcountry, 0, 238, Short.MAX_VALUE)
                                    .addComponent(secondcurrencyunit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnconvert)
                                .addGap(35, 35, 35)))
                        .addGap(52, 52, 52)
                        .addComponent(btnreset)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(firstcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(secondcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtsecond, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstcurrencyunit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondcurrencyunit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnconvert)
                    .addComponent(btnreset)
                    .addComponent(btnexit))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void firstcountryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_firstcountryItemStateChanged
        // TODO add your handling code here:
        
        int position = firstcountry.getSelectedIndex();

        firstcurrencyunit.setText(currencyUnits[position]);
        
    }//GEN-LAST:event_firstcountryItemStateChanged

    private void secondcountryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_secondcountryItemStateChanged
        // TODO add your handling code here:
        
        int position = secondcountry.getSelectedIndex();
     
        secondcurrencyunit.setText(currencyUnits[position]);
        
    }//GEN-LAST:event_secondcountryItemStateChanged

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnconvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconvertActionPerformed
        // TODO add your handling code here:
        
        //Convert currency
        
        if(firstcountry.getSelectedIndex()==0 || secondcountry.getSelectedIndex()==0 || txtfirst.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please select both countries and input the amount.","Error Message",JOptionPane.INFORMATION_MESSAGE);
            
            return;
  
        }    
        
        double amountToChange = Double.parseDouble(txtfirst.getText());
        double amountInPounds = 0.0;
        double amountChanged = 0.0;
        
        switch(firstcountry.getSelectedItem().toString())
        {
        case "Sri Lanka": amountInPounds = amountToChange / Sri_Lankan_Rupees;break;
        case "USA": amountInPounds = amountToChange / US_Dollar;break;
        case "Canada": amountInPounds = amountToChange / Canadian_Dollar;break;
        case "Japan": amountInPounds = amountToChange / Japanese_Yen;break;
        case "Italy": amountInPounds = amountToChange / Italy_Euro;break;
        case "Russia": amountInPounds = amountToChange / Russian_Ruble;break;
        case "Australia": amountInPounds = amountToChange / Australian_Dollar;break;
        case "China": amountInPounds = amountToChange / Chinese_Yuan;break;
        case "South Korea": amountInPounds = amountToChange / South_Korean_Won;break;
        case "Philippine": amountInPounds = amountToChange / Philippine_Peso;break;
        default:amountInPounds = 0.0;
    }//GEN-LAST:event_btnconvertActionPerformed

        //Amount is changed in Pounds
        
        switch(secondcountry.getSelectedItem().toString())
        {
        case "Sri Lanka": amountChanged = amountInPounds * Sri_Lankan_Rupees;break;
        case "USA": amountChanged = amountInPounds * US_Dollar;break;
        case "Canada": amountChanged = amountInPounds * Canadian_Dollar;break;
        case "Japan": amountChanged = amountInPounds * Japanese_Yen;break;
        case "Italy": amountChanged = amountInPounds * Italy_Euro;break;
        case "Russia": amountChanged = amountInPounds * Russian_Ruble;break;
        case "Australia": amountChanged = amountInPounds * Australian_Dollar;break;
        case "China": amountChanged = amountInPounds * Chinese_Yuan;break;
        case "South Korea": amountChanged = amountInPounds * South_Korean_Won;break;
        case "Philippine": amountChanged = amountInPounds * Philippine_Peso;break;
        default:amountChanged = amountInPounds * 0.0;
        }
        String value = String.format("%.2f",amountChanged);
        txtsecond.setText(value);
        }
        
        
    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        
        firstcountry.setSelectedIndex(0);
        secondcountry.setSelectedIndex(0);
        txtfirst.setText(null);
        txtsecond.setText(null);
    }//GEN-LAST:event_btnresetActionPerformed


     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mycurrencyconverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mycurrencyconverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mycurrencyconverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mycurrencyconverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mycurrencyconverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconvert;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnreset;
    private javax.swing.JComboBox<String> firstcountry;
    private javax.swing.JLabel firstcurrencyunit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> secondcountry;
    private javax.swing.JLabel secondcurrencyunit;
    private javax.swing.JTextField txtfirst;
    private javax.swing.JTextField txtsecond;
    // End of variables declaration//GEN-END:variables
}
